name: continuum
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  animated_text_kit: ^4.3.0
  audioplayers: ^6.5.1
  auto_size_text: ^3.0.0
  cloud_firestore: ^6.1.2
  cupertino_icons: ^1.0.5
  firebase_analytics: ^12.1.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  google_fonts: ^7.1.0
  google_sign_in: ^7.2.0
  graphify:
    path: ./packages/graphify
  json_annotation: ^4.8.1
  jumping_dot: ^0.0.7
  live_indicator: ^0.0.4
  mesh_gradient: ^1.3.8
  pointer_interceptor: ^0.10.1+2
  riverpod_annotation: ^4.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.10.5
  custom_lint: ^0.8.1
  flutter_lints: ">=3.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
