services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: continuum
      POSTGRES_PASSWORD: "SQoiJK6hKCCIi8e7nE37i7h53pCxqO_A"
    volumes:
      - continuum_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "3gbPh1N1Ky0jLFZKg9WAeKdMMrY4Dc3I"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: continuum_test
      POSTGRES_PASSWORD: "ouYInMc0TU6e8-nugufVAcYHzCNlsUFu"
    volumes:
      - continuum_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "53GI2DhRYpEpsSPkezZ-LgEnM89Hhx_r"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  continuum_data:
  continuum_test_data:
